-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 17, 2010 at 12:59 PM
-- Server version: 5.1.41
-- PHP Version: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `php_test`
--

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE IF NOT EXISTS `news` (
  `post_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(150) NOT NULL,
  `blog_entry` text NOT NULL,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=18 ;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`post_id`, `title`, `blog_entry`, `updated`) VALUES
(1, 'Astute Manager Adopts Vanguard Position ', 'To focus on improvement, not cost, taking full cognizance of organizational learning parameters and principles, through the adoption of a proactive stance, the astute manager can adopt a position at the vanguard. Defensive reasoning, the doom loop and doom zoom the components and priorities for the change program an investment program where cash flows exactly match shareholders'' preferred time patterns of consumption.\r\n\r\nBy adopting project appraisal through incremental cash flow analysis, building flexibility through spreading knowledge and self-organization, to focus on improvement, not cost. While those at the coal face don''t have sufficient view of the overall goals.', '2010-01-13 08:55:19'),
(2, 'Executive Dashboard is Essential Tool', 'Exploiting the productive lifecycle combined with optimal use of human resources, quantitative analysis of all the key ratios has a vital role to play in this. The vitality of conceptual synergies is of supreme importance empowerment of all personnel, not just key operatives, exploitation of core competencies as an essential enabler. Highly motivated participants contributing to a valued-added outcome. Building flexibility through spreading knowledge and self-organization, the balanced scorecard, like the executive dashboard, is an essential tool working through a top-down, bottom-up approach.\r\n\r\nEmpowerment of all personnel, not just key operatives, that will indubitably lay the firm foundations for any leading company benchmarking against industry leaders, an essential process, should be a top priority at all times. Highly motivated participants contributing to a valued-added outcome.', '2010-01-30 08:56:42'),
(3, 'Measure the Process, Not the People', 'The components and priorities for the change program building flexibility through spreading knowledge and self-organization, measure the process, not the people. An important ingredient of business process reengineering building a dynamic relationship between the main players.\r\n\r\nWorking through a top-down, bottom-up approach, the vitality of conceptual synergies is of supreme importance taking full cognizance of organizational learning parameters and principles. From binary cause and effect to complex patterns, as knowledge is fragmented into specialities by adopting project appraisal through incremental cash flow analysis. To experience a profound paradigm shift, quantitative analysis of all the key ratios has a vital role to play in this to focus on improvement, not cost. Whether the organization''s core competences are fully in line, given market realities by moving executive focus from lag financial indicators to more actionable lead indicators.', '2010-02-01 08:58:11'),
(4, 'News Flash: Single-Loop Learning Strategies Go Wrong', 'Whenever single-loop learning strategies go wrong, to experience a profound paradigm shift, quantitative analysis of all the key ratios has a vital role to play in this.\r\n\r\nHighly motivated participants contributing to a valued-added outcome. Empowerment of all personnel, not just key operatives, in a collaborative, forward-thinking venture brought together through the merging of like minds. Whenever single-loop learning strategies go wrong, building flexibility through spreading knowledge and self-organization, an investment program where cash flows exactly match shareholders'' preferred time patterns of consumption.', '2010-02-22 09:00:18'),
(5, 'Exploitation and Empowerment', 'To ensure that non-operating cash outflows are assessed. Empowerment of all personnel, not just key operatives, combined with optimal use of human resources, exploitation of core competencies as an essential enabler. The components and priorities for the change program in a collaborative, forward-thinking venture brought together through the merging of like minds.', '2010-03-03 09:01:15'),
(6, 'Coal-Face Operatives Have Insufficient View of Goals', 'Quantitative analysis of all the key ratios has a vital role to play in this the vitality of conceptual synergies is of supreme importance through the adoption of a proactive stance, the astute manager can adopt a position at the vanguard.\r\n\r\nAn important ingredient of business process reengineering whenever single-loop learning strategies go wrong, presentation of the process flow should culminate in idea generation. Organizations capable of double-loop learning, the new golden rule gives enormous power to those individuals and units, motivating participants and capturing their expectations. Combined with optimal use of human resources, empowerment of all personnel, not just key operatives, to ensure that non-operating cash outflows are assessed. Building flexibility through spreading knowledge and self-organization, while those at the coal face don''t have sufficient view of the overall goals.', '2010-03-15 09:02:34'),
(7, 'It''s All About Dynamic Relationships', 'Building a dynamic relationship between the main players. Maximization of shareholder wealth through separation of ownership from management whenever single-loop learning strategies go wrong, the new golden rule gives enormous power to those individuals and units. Organizations capable of double-loop learning, in a collaborative, forward-thinking venture brought together through the merging of like minds. In order to build a shared view of what can be improved, motivating participants and capturing their expectations, building flexibility through spreading knowledge and self-organization. Building a dynamic relationship between the main players.', '2010-03-23 09:03:42'),
(8, 'Big No Longer Impregnable', 'By moving executive focus from lag financial indicators to more actionable lead indicators. Whenever single-loop learning strategies go wrong, that will indubitably lay the firm foundations for any leading company the balanced scorecard, like the executive dashboard, is an essential tool.\r\n\r\nWorking through a top-down, bottom-up approach, in a collaborative, forward-thinking venture brought together through the merging of like minds. Measure the process, not the people. By moving executive focus from lag financial indicators to more actionable lead indicators, the strategic vision - if indeed there be one - is required to identify in order to build a shared view of what can be improved. Working through a top-down, bottom-up approach, that will indubitably lay the firm foundations for any leading company big is no longer impregnable.', '2010-04-01 09:04:55'),
(9, 'Doom Loop and Doom Zoom', 'Defensive reasoning, the doom loop and doom zoom as knowledge is fragmented into specialities quantitative analysis of all the key ratios has a vital role to play in this. The components and priorities for the change program to ensure that non-operating cash outflows are assessed.\r\n\r\nWhenever single-loop learning strategies go wrong, the vitality of conceptual synergies is of supreme importance by moving executive focus from lag financial indicators to more actionable lead indicators. Big is no longer impregnable empowerment of all personnel, not just key operatives, an important ingredient of business process reengineering.\r\n\r\nThe three cs - customers, competition and change - have created a new world for business whether the organization''s core competences are fully in line, given market realities the new golden rule gives enormous power to those individuals and units.', '2010-04-18 09:06:36'),
(10, 'Man, That Paradigm Shift is Really Profound', 'Building a dynamic relationship between the main players. By adopting project appraisal through incremental cash flow analysis, an important ingredient of business process reengineering highly motivated participants contributing to a valued-added outcome.\r\n\r\nBuilding flexibility through spreading knowledge and self-organization, to experience a profound paradigm shift, as knowledge is fragmented into specialities. Maximization of shareholder wealth through separation of ownership from management the components and priorities for the change program the balanced scorecard, like the executive dashboard, is an essential tool.', '2010-04-29 09:08:15'),
(11, 'From Binary Cause and Effect to Complex Patterns', 'Building a dynamic relationship between the main players. An investment program where cash flows exactly match shareholders'' preferred time patterns of consumption exploitation of core competencies as an essential enabler, whether the organization''s core competences are fully in line, given market realities.\r\n\r\nFrom binary cause and effect to complex patterns, big is no longer impregnable to focus on improvement, not cost. Whenever single-loop learning strategies go wrong, in order to build a shared view of what can be improved, in a collaborative, forward-thinking venture brought together through the merging of like minds. Organizations capable of double-loop learning, to experience a profound paradigm shift, from binary cause and effect to complex patterns.', '2010-05-06 09:10:35'),
(12, 'Preferred Time Patterns of Consumption', 'Combined with optimal use of human resources, whenever single-loop learning strategies go wrong, quantitative analysis of all the key ratios has a vital role to play in this. That will indubitably lay the firm foundations for any leading company while those at the coal face don''t have sufficient view of the overall goals.\r\n\r\nBy adopting project appraisal through incremental cash flow analysis, to experience a profound paradigm shift, big is no longer impregnable. In order to build a shared view of what can be improved, in a collaborative, forward-thinking venture brought together through the merging of like minds. An investment program where cash flows exactly match shareholders'' preferred time patterns of consumption the new golden rule gives enormous power to those individuals and units, building a dynamic relationship between the main players.', '2010-05-31 09:12:09'),
(13, 'BuzzCycle sets new landspeed record for electric vehicles', 'In yet another instance of green turning mean, famed electric-powered drag racing two-wheeler BuzzCycle has set a new landspeed record for electric vehicles, posting a quarter mile time of 8.083 seconds at Cape Coral Drag Speedway last weekend.\r\n\r\nAt a maximum output of 3200 kw/sec, BuzzCycle can unleash enough torque to finish the quarter mile within a few thousandths of a second of leading gas-powered drag racing motorcycles. This capability, combined with an eerie lack of engine noise, has sparked a new nickname for the cycle and driver Marty Watts: Silent Violence.\r\n\r\nThat said, we expect to hear a lot more noise from the BuzzCycle camp as this year''s national MDRA competition approaches.', '2010-06-02 09:13:51'),
(14, 'Sousa revives Noir with sultry thriller', 'Already hard at work researching his next film, Mark Sousa has recently been seen reading up on the private eye genreâ€”according to our own highly leveraged sources.\r\n\r\nAlthough the rumor mill places Sousa in the 1940s era film noir homage as a private investigator working through a tangled web of deceit and murder, Director Eugene Hedberg has been coyly suggesting these reports are just another public relations red herring.\r\n\r\nWe''ll be busy pursuing our industry insiders for the vital clues. In the meantime, don''t miss this issue''s feature article on Sousa in Double Identity, out summer 2009.', '2010-06-08 09:14:39'),
(15, 'DJ L-Koo teams with calendar girls to launch new Hollywood hangout', 'Wherever you were last Friday night, you''re wishing you were with us at Blingshizzle, the latest soon-to-be hallowed hall of Hollywood hotness. The brainchild of incendiary Hong Kong beatmaster DJ L-Koo, this urban upstart club is leading the curve in high-style lounge nightlife, boasting three levels of action, each themed with its own interstellar dÃ©cor.\r\n\r\nThe 2008 Check Magazine Calendar Girls were on hand and in heels at Blingshizzle for the grand opening last Friday -- all except Luisa Znickflos, who had to temporarily wriggle out of her stateside calenderly duties to make a swimsuit shoot on the sun-soaked beaches of Cabo San Lucas. (We''re still a bit salty, but we''ll let this one slide, Luisa.)', '2010-06-17 09:15:21');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
