#include <stdio.h>
#include <stdlib.h>

//#include <iostream>

/*
#include <stdio.h>
#include <stdlib.h>
#include <stm.h>
#include <string.h>
#include <strings.h>
#include <strmif.h>
#include <subauth.h>
#include <svcguid.h>
#include <symcat.h>
#include <tchar.h>
#include <time.h>
#include <tlhelp32.h>
#include <tmschema.h>
#include <unistd.h>
#include <unknwn.h>
#include <userenv.h>
#include <usp10.h>
#include <utime.h>
#include <uxtheme.h>
#include <values.h>
#include <varargs.h>
#include <vfw.h>
#include <vidcap.h>
#include <vmr9.h>
#include <vptype.h>
#include <w32api.h>
#include <wchar.h>
#include <wctype.h>
#include <winable.h>
#include <winbase.h>
#include <winber.h>
#include <wincon.h>
#include <wincrypt.h>
#include <windef.h>
#include <windns.h>
#include <windows.h>
#include <windowsx.h>
#include <winerror.h>
#include <wingdi.h>
#include <wininet.h>
#include <winioctl.h>
#include <winldap.h>
#include <winnetwk.h>
#include <winnls.h>
#include <winnt.h>
#include <winperf.h>
#include <winreg.h>
#include <winresrc.h>
#include <winsnmp.h>
#include <winsock.h>
#include <winsock2.h>
#include <winspool.h>
#include <winsvc.h>
#include <winuser.h>
#include <winver.h>
#include <ws2pi.h>
#include <ws2tcpip.h>
#include <wsahelp.h>
#include <wspix.h>
#include <wsnetbs.h>
#include <wtsapi32.h>
#include <wtypes.h>
#include <xprtdefs.h>
#include <zmouse.h>
*/